spring.application.name=Week13Example
spring.freemarker.settings.object_wrapper=no.api.freemarker.java8.Java8ObjectWrapper(Configuration.VERSION_2_3_33)
spring.datasource.url=jdbc:mysql://localhost/cs3220
spring.datasource.username=cs3220
spring.datasource.password=test123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true